apiVersion: v1
kind: ConfigMap
metadata:
   name: mcloud1-cfg
   namespace: dev
data:
   ENV: "dev"
   HOST: "10.10.2.1"
   TZ: "America/Bogota"
   
   data.json: |
     {
       "ciudad": "peru",
       "curso": "k8s"
     }