# Usa una imagen base de Python
FROM python:3.9-slim

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el código fuente de la aplicación al contenedor
COPY . /app



# Comando para ejecutar la aplicación
CMD ["python", "task.py"]

