version: '3'

services:
  micro1:
    image: mauron/mcloud1:2a
    container_name: micro1
    ports:
      - "7001:8080"
    volumes:
      - /home/azureuser/html:/data
    environment:
      - TZ=America/Bogota
      - ENV=prd
      - HOST=12.12.12.02
    networks:
      - micros

networks:
  micros:
   name: micros
   external: true
  