version: '3'

services:
  mcloud1:
    image: mauron/mcloud1:2a
    container_name: micro1
    ports:
      - "7001:8080"
    volumes:
      - /home/azureuser/html:/data
    environment:
      - TZ=America/Bogota
      - ENV=prd
      - HOST=micro3
    networks:
      - micros

networks:
  micros:
   name: micros
   external: true
  