apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcloud1
  namespace: sabado
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcloud1
  template:
    metadata:
      labels:
        app: mcloud1
    spec:
      containers:
      - name: mcloud1
        image: mauron/mcloud1:2a
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: mcloud1-cfg
        volumeMounts:
        - name: config-json
          mountPath: /data
          subPath: data.json
      
      volumes:
      - name: config-json
        configMap:
           name: mcloud1-cfg
