apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro3
  namespace: sabado
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro3
  template:
    metadata:
      labels:
        app: micro3
    spec:
      containers:
      - name: micro3
        image: mauron/mcloud1:2a
        ports:
        - containerPort: 8080
        env:
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: micro3-cfg
              key: "ENV"
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: micro3-cfg
              key: "HOST"
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: micro3-cfg
              key: "TZ"
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 11
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 3            

