apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro3
  namespace: sabado
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro3
  template:
    metadata:
      labels:
        app: micro3
    spec:
      containers:
      - name: micro3
        image: mauron/mcloud1:2a
        ports:
        - containerPort: 8080
        env:
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: micro3-cfg
              key: "ENV"
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: micro3-cfg
              key: "HOST"
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: micro3-cfg
              key: "TZ"

