apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: micro3-hpa
  namespace: sabado
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: micro3
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 90