apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: sabado
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi