apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mcloud1-stfs
  namespace: sabado
spec:
  replicas: 1
  serviceName: mcloud1-stfs
  selector:
    matchLabels:
      app: mcloud1-stfs
  template:
    metadata:
      labels:
        app: mcloud1-stfs
    spec:
      containers:
      - name: mcloud1-stfs
        image: mauron/mcloud1:2a
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: mcloud13-cfg
        volumeMounts:
        - name: pvc-mcloud1
          mountPath: /vol
    
      volumes:
      - name: pvc-mcloud1
        persistentVolumeClaim:
          claimName: local-pvc
