apiVersion: v1
kind: Service
metadata:
  name: micro3-service
  namespace: qa
spec:
  selector:
    app: micro3
  ports:
    - protocol: TCP
      port: 7010
      targetPort: 8080
  type: LoadBalancer
